const express = require("express");
const app = express();
app.use(express.json());
require("./db/connection");
const { Mongoose } = require("mongoose");
const {createPost}=require("./ExportFuns/createPost");
const {getPost}=require("./ExportFuns/getPost");
const {updatePost}=require("./ExportFuns/updatePost");
const {deletePost}=require("./ExportFuns/deletePost");
const{createUser}=require("./ExportFuns/createUser");
const{deleteUser}=require("./ExportFuns/deleteUser");
const{loginUser}=require("./ExportFuns/login");
const port = process.env.PORT || 3000;
app.post("/articales", createPost);
app.get("/articales",getPost);
app.patch("/update/:id",updatePost);
app.delete("/deleteArti/:id", deletePost);
app.post("/signup", createUser);
app.post("/login",loginUser);
app.delete("/delete/:id", deleteUser);
app.listen(port, () => console.log(`sending to port ${port}`));